/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gerry_andersons_thunderbird_iv - ralphs workshop.glb --types --keepnames 
Author: Ralph's Workshop (https://sketchfab.com/RalphEdenbag)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gerry-andersons-thunderbird-iv-476f49fe0ca840dcab1b11da3c26fe1c
Title: Gerry Anderson's Thunderbird IV
*/

import * as THREE from 'three'
import { forwardRef, type FC, JSX, useRef, useImperativeHandle } from 'react'
import { useGLTF } from '@react-three/drei'

const ThunderbirdFour = forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const group = useRef<THREE.Group>(null)
  useImperativeHandle(ref, () => group.current as THREE.Group)
  const { nodes, materials } = useGLTF('/models/thunderbird4.glb') as any

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Circle001_14" position={[0.064, 0.042, -0.113]} rotation={[-0.436, 0, 0]}>
                <mesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials['Jaune.001']} />
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.Emission} />
                <mesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Metal} />
              </group>
              <group name="Cube_0" scale={0.151}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.Jaune} />
                <mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.Rouge} />
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.Gris} />
                <mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Metal} />
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Noir} />
                <mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials['Jaune.002']} />
              </group>
              <group name="Cube002_1" scale={0.151}>
                <mesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials.Glass} />
              </group>
              <group name="Circle_2" position={[0, -0.047, -0.031]} rotation={[-1.098, 0, 0]} scale={0.005}>
                <mesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['Jaune.001']} />
              </group>
              <group name="Cube003_3" scale={0.151}>
                <mesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.Gris} />
              </group>
              <group name="Sticker_Thunderbird_4_5" position={[0.075, 0.11, -0.329]} rotation={[Math.PI / 2, 0.447, -Math.PI / 2]} scale={0.058}>
                <mesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.Sticker_Thunderbird_4} />
              </group>
              <group name="Sticker_Thunderbird_4001_6" position={[0.082, 0.098, -0.331]} rotation={[Math.PI / 2, 0.432, -Math.PI / 2]} scale={0.053}>
                <mesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.Sticker_Thunderbird_4} />
              </group>
              <group name="Sticker_Thunderbird_4002_7" position={[0.008, 0.178, -0.399]} rotation={[Math.PI / 2, -0.008, -Math.PI / 2]} scale={[0.058, 0.06, 0.066]}>
                <mesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Sticker_Thunderbird_4} />
              </group>
              <group name="Sticker_Thunderbird_4003_8" position={[0.004, 0.074, -0.47]} rotation={[1.553, 0.019, 3.136]} scale={0.111}>
                <mesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Sticker_Thunderbird_4} />
              </group>
              <group name="Sticker_Thunderbird_4004_9" position={[0.075, 0.11, -0.329]} rotation={[Math.PI / 2, 0.447, -Math.PI / 2]} scale={0.058}>
                <mesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Sticker_Thunderbird_4} />
              </group>
              <group name="Sticker_Thunderbird_4005_10" position={[-0.001, 0.084, -0.453]} rotation={[1.799, 0, -Math.PI]} scale={0.034}>
                <mesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Sticker_Thunderbird_4} />
              </group>
              <group name="Sticker_Thunderbird_4006_11" position={[-0.074, 0.11, -0.329]} rotation={[Math.PI / 2, -0.447, Math.PI / 2]} scale={0.058}>
                <mesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials.Sticker_Thunderbird_4} />
              </group>
              <group name="Sticker_Thunderbird_4007_12" position={[-0.081, 0.098, -0.331]} rotation={[Math.PI / 2, -0.432, Math.PI / 2]} scale={0.053}>
                <mesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.Sticker_Thunderbird_4} />
              </group>
              <group name="Sticker_Thunderbird_4008_13" position={[-0.007, 0.178, -0.399]} rotation={[Math.PI / 2, 0.008, Math.PI / 2]} scale={[0.058, 0.06, 0.066]}>
                <mesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.Sticker_Thunderbird_4} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
})

useGLTF.preload('/models/thunderbird4.glb')

export default ThunderbirdFour
ThunderbirdFour.displayName = 'ThunderbirdFour' 
